title = "Gitleaks Custom Rules"

[extend]
useDefault = true

[[rules]]
id = "exclude PASSWORD="
description = "checks for instances of PASSWORD= followed by digits"
regex = '''PASSWORD=[0-9]{0,20}'''

[allowlist]
description = "allow README, for examples"
paths = [
    '''README.md'''
]